# Generated by Django 5.1.1 on 2025-05-20 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0002_faculty_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='name',
        ),
        migrations.AddField(
            model_name='faculty',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
